name: Comment Artifacts on PR

on:
  workflow_run:
    workflows: [ "Upload Artifacts" ]
    types: [ completed ]

permissions:
  pull-requests: write  # For commenting on PRs
  contents: read        # For accessing repo data if needed

jobs:
  comment:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.event == 'pull_request' }}
    steps:
      - name: Delete old comments and post new one
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const runId = process.env.RUN_ID;
            const prNumber = process.env.PR_NUMBER;

            // Exit if no PR number (safety check)
            if (!prNumber) {
              console.log("No PR number found in workflow_run event. Skipping.");
              return;
            }

            // Fetch existing comments to delete old ones
            const comments = await github.rest.issues.listComments({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: Number(prNumber),  // Ensure it's a number
            });
            const oldComments = comments.data.filter(comment => 
              comment.body.startsWith("✅ Artifacts uploaded!")
            );
            for (const comment of oldComments) {
              await github.rest.issues.deleteComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                comment_id: comment.id,
              });
              console.log(`Deleted old comment ID: ${comment.id}`);
            }

            // Fetch artifacts for the workflow run
            const artifacts = await github.rest.actions.listWorkflowRunArtifacts({
              owner: context.repo.owner,
              repo: context.repo.repo,
              run_id: Number(runId),  // Ensure it's a number
            });

            // Find the two artifacts
            const artifact1 = artifacts.data.artifacts.find(a => a.name === 'quick-test-1');
            const artifact2 = artifacts.data.artifacts.find(a => a.name === 'quick-test-2');
            if (!artifact1 || !artifact2) {
              console.log("One or both artifacts ('quick-test-1', 'quick-test-2') not found.");
              return;
            }

            // Construct artifact download URLs
            const artifactUrl1 = `https://github.com/${context.repo.owner}/${context.repo.repo}/actions/runs/${runId}/artifacts/${artifact1.id}`;
            const artifactUrl2 = `https://github.com/${context.repo.owner}/${context.repo.repo}/actions/runs/${runId}/artifacts/${artifact2.id}`;

            // Post the updated comment
            const commentBody = `✅ Artifacts uploaded!  
            - 📄 [Download quick-test-1](${artifactUrl1})  
            - 📄 [Download quick-test-2](${artifactUrl2})`;
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: Number(prNumber),
              body: commentBody
            });
            console.log("Posted new comment with artifact links.");
        env:
          RUN_ID: ${{ github.event.workflow_run.id }}
          PR_NUMBER: ${{ github.event.workflow_run.pull_requests[0].number }}