name: Upload Artifacts

on:
  pull_request:
    branches: [ master ]  

concurrency:
  group: build-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

permissions:
  contents: read  

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create dummy files and metadata
        run: |
          echo "This is test file 1" > ./quick-test-1.txt
          echo "This is test file 2" > ./quick-test-2.txt
          # Create a JSON file with PR number
          echo "{\"pr_number\": ${{ github.event.pull_request.number || 'null' }}, \"ref\": \"${{ github.ref }}\"}" > workflow-info.json

      - name: Upload first artifact
        uses: actions/upload-artifact@v4
        with:
          name: quick-test-1
          path: ./quick-test-1.txt

      - name: Upload second artifact
        uses: actions/upload-artifact@v4
        with:
          name: quick-test-2
          path: ./quick-test-2.txt

      - name: Upload workflow info artifact
        uses: actions/upload-artifact@v4
        with:
          name: workflow-info
          path: ./workflow-info.json